image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 15 x64
  - npm install

build_script:
  - npm run dist

test: off

artifacts:
  - path: dist\crmbar*Setup*.exe
    name: Setup
